
version: 2

models:
  - name: customer_orders
    description: "Dummy join of customers with orders"
  - name: high_value_customers_with_no_orders
    description: "Dummy projection of customer_orders with filtering logic"
  - name: customer_total_order_price
    description: "Dummy sum of order price by customer"

sources:
  - name: snowflakesampledata
    database: snowflake_sample_data
    schema: tpch_sf1
    tables:
      - name: orders
      - name: customer
