---
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
name: Run unit tests

jobs:
  run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.workflow_run.head_branch }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt
    - name: Run tests
      run: |
        cd dbt_python_model_testing_exploration
        python -m pytest tests
      env:
        SNOWFLAKE_CONN_STR: ${{ secrets.SNOWFLAKE_CONN_STR }}
        SNOWFLAKE_TARGET_SCHEMA: ${{ secrets.SNOWFLAKE_TARGET_SCHEMA }}
